train : /train
valid : /valid
num_classes : 8
backbone : resnet50
batch_size : 8
device : 'cuda:0'
gpu: 0
epochs : 40
workers : 12
learning_rate : 0.02
momentum : 0.9
weight_decay : 1e-4
print_frequency : 100
lr_step_size : 8
lr_steps : [8, 11]
lr_gamma : 0.1
test_only : False
output_dir : ./pretrained
aspect_ratio_group_factor : 3
early_stopping : 10
debug : 3
distributed : True
parallel : False
world_size : 1
pretrained : False
trainable_backbone_layers: 5
resume : './pretrained/model_0.pth'
visualize : True
